app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#home_page:
#    path: /
#    defaults: { _controller: AppBundle:Default:index }

show_all_reservation_slot:
    path: /reservation
    defaults: { _controller: AppBundle:ReservationSlot:showAll }

create_reservation_slot:
    path: /reservation/create
    defaults: { _controller: AppBundle:ReservationSlot:create }

update_reservation_slot:
    path: /reservation/{id}/update
    defaults: { _controller: AppBundle:ReservationSlot:update }

delete_reservation_slot:
    path: /reservation/{id}/delete
    defaults: { _controller: AppBundle:ReservationSlot:delete }

add_visitor:
    path: /reservation/{reservationSlotId}/visitor/create
    defaults: { _controller: AppBundle:Visitor:create }

delete_visitor:
    path: /visitor/{id}/delete
    defaults: { _controller: AppBundle:Visitor:delete }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout
