app:
    resource: "@AppBundle/Controller/"
    type:     annotation

show_all_reservation_slot:
    path: /
    defaults: { _controller: AppBundle:ReservationSlot:showAll }

create_reservation_slot:
    path: /create
    defaults: { _controller: AppBundle:ReservationSlot:create }

update_reservation_slot:
    path: /{id}/update
    defaults: { _controller: AppBundle:ReservationSlot:update }

delete_reservation_slot:
    path: /{id}/delete
    defaults: { _controller: AppBundle:ReservationSlot:delete }

add_visitor:
    path: /{reservationSlotId}/visitor/create
    defaults: { _controller: AppBundle:Visitor:create }

delete_visitor:
    path: /visitor/{id}/delete
    defaults: { _controller: AppBundle:Visitor:delete }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout
