app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home_page:
    path: /
    defaults: { _controller: AppBundle:Default:index }

create_reservation_slot:
    path: /reservation/create
    defaults: { _controller: AppBundle:ReservationSlot:create }

show_all_reservation_slot:
    path: /reservation
    defaults: { _controller: AppBundle:ReservationSlot:showAll }
