controllers:
    resource: "../src/Controller/"
    type: annotation

app_logout:
    path: /logout

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#show_all_reservation_slot:
#  path: /
#  controller: App\Controller\ReservationSlotController::showAllAction
#
#create_reservation_slot:
#  path: /create
#  controller: App\Controller\ReservationSlotController::createAction
#
#add_visitor:
#  path: /{reservationSlotId}/visitor/create
#  defaults: { _controller: AppBundle:Visitor:create }
#
#create_sport:
#  path: /sport/create
#  defaults: { _controller: AppBundle:Sport:create }
