AppBundle\Entity\ReservationSlot:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
        location:
            type: string
            length: 100
            nullable: true
        lector:
            type: string
            length: 100
            nullable: true
        level:
            type: string
            length: 100
            nullable: true
        capacity:
            type: integer
        note:
            type: string
            length: 255
            nullable: true
